version: "3.8"

name: menged
services:
  postgis:
    image: postgis/postgis
    container_name: menged-dev-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: gtfs_dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
  otp:
    image: opentripplanner/opentripplanner:latest
    container_name: otp-routing
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./otp-data:/var/opentripplanner
    command: "--build --save --serve"

volumes:
  postgis_data:
